#!/usr/bin/env bash
# Copies SpectrumVision into a robot project, for its WPILib version:
#   robot-vision/install.sh ROBOT_PROJECT_DIR 2026     (roboRIO: WPILib 2026, PhotonLib 2026)
#   robot-vision/install.sh ROBOT_PROJECT_DIR 2027     (SystemCore: WPILib 2027 alpha-6, PhotonLib 2027 alpha-2)
# It replaces src/main/java/org/spectrum3847/vision in that project (your own code isn't touched)
# and needs only Python 3 and Bash; the 2027 copy is generated by tools/port2027.py.
# The project must already have the PhotonLib vendordep for the same year.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
dest=${1:?usage: install.sh ROBOT_PROJECT_DIR 2026|2027}
year=${2:?usage: install.sh ROBOT_PROJECT_DIR 2026|2027}
[[ -f $dest/build.gradle ]] || { echo "$dest has no build.gradle: not a robot project" >&2; exit 1; }
target=$dest/src/main/java/org/spectrum3847/vision
case $year in
  2026) src=$HERE/src/main/java/org/spectrum3847/vision ;;
  2027)
    tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
    python3 "$HERE/tools/port2027.py" "$tmp" >/dev/null
    src=$tmp/main/java/org/spectrum3847/vision ;;
  *) echo "year must be 2026 or 2027" >&2; exit 2 ;;
esac
ls "$dest"/vendordeps/*hoton* >/dev/null 2>&1 || echo "WARNING: no PhotonLib vendordep in $dest/vendordeps (add it in VS Code: Manage Vendor Libraries)"
rm -rf "$target"
mkdir -p "$target"
cp -r "$src"/. "$target"/
mkdir -p "$target/compat"
cp "$HERE/src/compat$year/java/org/spectrum3847/vision/compat/"*.java "$target/compat/"
echo "SpectrumVision ($year) copied to $target ($(find "$target" -name '*.java' | wc -l) files)."
echo "Version: $(git -C "$HERE" rev-parse --short HEAD 2>/dev/null || echo unknown) — note it in your commit."
