// Definitions shown when hovering a <span class="term">. Keys match the term's text
// (or its data-term). Keep each to one or two plain sentences.
Object.assign(Site.glossary, {
  'AprilTag': 'A black-and-white square marker, like a simple QR code, that a computer can find quickly and identify by its ID number.',
  'SBC': 'Single-board computer: a whole computer (processor, memory, ports) on one small circuit board. A Raspberry Pi and a Jetson are both SBCs.',
  'coprocessor': 'A second computer on the robot that does one heavy job (here, vision) so the main robot controller doesn\'t have to.',
  'SystemCore': 'The new FRC robot controller (replacing the roboRIO). It runs the robot code and talks to the Jetson over Ethernet.',
  'pose': 'Where something is (x, y, z) and which way it is facing (roll, pitch, yaw). A robot\'s field pose is its position and heading on the field.',
  'CPU': 'Central Processing Unit: a few very fast, very flexible cores that run programs step by step. The Jetson has 6.',
  'GPU': 'Graphics Processing Unit: hundreds or thousands of small cores that all do the same simple job on different data at once. Ours has 1,024.',
  'CUDA': 'NVIDIA\'s way of writing programs that run on the GPU. Our AprilTag detector is written in CUDA.',
  'core': 'One independent worker inside a processor. A 6-core CPU can run 6 things at the same instant.',
  'RAM': 'Random-access memory: the fast, temporary workspace where programs keep the data they\'re using. Cleared when power is lost.',
  'SSD': 'Solid-state drive: permanent storage made of flash memory. Our Jetson boots Linux from a 256 GB NVMe SSD.',
  'NVMe': 'A fast way to connect an SSD straight to the processor over PCIe lanes instead of an older, slower disk connection.',
  'PCIe': 'PCI Express: a high-speed connection between a processor and devices like SSDs and Wi-Fi cards.',
  'USB': 'Universal Serial Bus. Our cameras use USB 2.0 (480 Mbit/s total, shared by every USB 2.0 device on the Jetson).',
  'MJPEG': 'Motion JPEG: video sent as a stream of separate JPEG pictures. Our cameras compress every frame as a JPEG before sending it.',
  'JPEG': 'A way of compressing photos by throwing away detail your eye won\'t miss. It makes a 1 MB frame about 50 KB.',
  'global shutter': 'Every pixel on the sensor starts and stops collecting light at the same moment, so fast motion isn\'t skewed.',
  'rolling shutter': 'The sensor collects light one row at a time, top to bottom, so fast-moving things come out slanted or wobbly.',
  'exposure': 'How long the sensor collects light for each frame. Longer is brighter but blurrier.',
  'gain': 'Electronic amplification of the sensor signal. Brightens the image, but amplifies the noise too.',
  'latency': 'Delay: how long between something happening (the camera capturing a frame) and the robot getting the answer.',
  'frame': 'One single picture from the camera. At 120 fps, a new frame every 8.3 milliseconds.',
  'fps': 'Frames per second. Our cameras run at 120.',
  'pixel': 'One tiny dot of the picture. Our cameras have 1280 × 800 = 1,024,000 of them.',
  'Linux': 'A free, open-source operating system. The Jetson runs Ubuntu Linux; so do most servers, Android phones and the SystemCore.',
  'kernel': 'The core of the operating system: it controls the hardware, memory and which program runs when.',
  'driver': 'Code inside the kernel that knows how to talk to one kind of hardware, like USB cameras (uvcvideo).',
  'PhotonVision': 'Free, open-source vision software used by many FRC teams. It runs on the coprocessor and sends targets to the robot.',
  'NetworkTables': 'WPILib\'s system for sharing values between robot code, dashboards and coprocessors over the network.',
  'PhotonLib': 'The library robot code uses to read PhotonVision\'s results.',
  'thread': 'One sequence of instructions a program runs. A program can have many threads running on different cores at once.',
  'watchdog': 'A timer that must be reset regularly. If the thing it watches stops resetting it (because it froze), the watchdog restarts it.',
  'intrinsics': 'A camera\'s own properties: focal length, image center and lens distortion. Found by calibration.',
  'extrinsics': 'Where a camera is mounted and which way it points, relative to the robot (or the world).',
  'distortion': 'How a real lens bends straight lines into curves, especially near the edges of the image.',
  'reprojection error': 'How far (in pixels) the calibration\'s predicted corner positions land from where the corners were really seen.',
  'PnP': 'Perspective-n-Point: the math that finds a camera\'s pose from known 3D points and where they appear in the image.',
  'ambiguity': 'When two different poses would make a tag look almost the same in the image, so the solver can\'t be sure which is real.',
  'gyro': 'A sensor that measures rotation. The robot\'s gyro (IMU) knows its heading very accurately.',
  'timestamp': 'A record of exactly when something happened, like when a frame was captured.',
  'decision margin': 'How confidently a tag\'s bits were read: on average, how far each bit\'s brightness sits from the black/white cut-off. Higher is more trustworthy; PhotonVision drops tags below its cutoff (we use 15).',
  'Hamming distance': 'How many bits differ between two codes. Tag codes are chosen so every pair differs by at least 11 bits.',
  'JetPack': 'NVIDIA\'s software bundle for Jetson: Ubuntu Linux plus drivers, CUDA, TensorRT and tools.',
  'SoC': 'System on a Chip: the CPU, GPU, memory controller and special engines all on one piece of silicon.',
  'NVJPG': 'A hardware JPEG decoder built into the Jetson\'s chip. It decodes camera frames without using the CPU.',
  'bandwidth': 'How much data a connection can carry per second.',
  'patch': 'A file describing changes to someone else\'s code: which lines to remove and which to add.',
  'open source': 'Software whose code anyone can read, change and share. PhotonVision, Linux and WPILib are all open source.',
  'OV9281': 'The OmniVision image sensor inside the Thriftiest Cam: 1280 × 800, monochrome, global shutter, up to 120 fps.',
  'monochrome': 'Black-and-white (grayscale) only. Every pixel measures brightness, with no color filter in the way.',
  'ChArUco': 'A calibration board: a chessboard whose white squares hold small ArUco markers, so every corner can be identified.',
  'homography': 'A math transform that maps a flat square in the world to the four-sided shape it makes in the image.',
  'DMA': 'Direct Memory Access: hardware copying data into memory by itself, without the CPU moving each byte.',
  'unified memory': 'On the Jetson, the CPU and GPU share the same physical RAM, so data doesn\'t have to cross a slow bus to reach the GPU.',
  'odometry': 'Estimating how far the robot has moved from its wheel encoders and gyro.',
  'Kalman filter': 'A way of blending several noisy measurements (odometry, vision) into one best estimate, trusting each by how accurate it is.',
  'time sync': 'Agreeing on the time between two computers, so a timestamp from the Jetson means the same moment on the robot.',
  'systemd': 'The Linux program that starts services at boot, restarts them if they crash and runs the watchdog.',
  'TensorRT': 'NVIDIA\'s engine for running neural networks fast on the GPU. We use it for game-piece detection.',
  'YOLO': '"You Only Look Once": a family of neural networks that find objects (like game pieces) in an image.',
  'microframe': 'USB 2.0 splits time into 125-microsecond slices (8,000 a second). A camera reserves a fixed number of bytes in every one.',
  'warp': 'A group of 32 GPU threads that run the same instruction at the same time.',
  'kernel (GPU)': 'A small function that runs on the GPU, once per thread, thousands of times in parallel.',
  'IDCT': 'Inverse discrete cosine transform: the math step of JPEG decoding that turns frequency numbers back into pixels.',
});
